name: test
on:
- pull_request
defaults: { run: { shell: bash } }
jobs:
  sql-kit_all:
    strategy:
      fail-fast: false
      matrix:
        image:
          # 5.2 Stable
          - swift:5.2-xenial
          - swift:5.2-bionic
          - swift:5.2-focal
          - swift:5.2-centos8
          - swift:5.2-amazonlinux2
          # 5.2 Unstable
          - swiftlang/swift:nightly-5.2-xenial
          - swiftlang/swift:nightly-5.2-bionic
          # 5.3 Unstable
          - swiftlang/swift:nightly-5.3-xenial
          - swiftlang/swift:nightly-5.3-bionic
          # Master Unstable
          - swiftlang/swift:nightly-master-xenial
          - swiftlang/swift:nightly-master-bionic
          - swiftlang/swift:nightly-master-focal
          - swiftlang/swift:nightly-master-centos8
          - swiftlang/swift:nightly-master-amazonlinux2
        include:
          - { os: 'ubuntu-latest' }
          - { os: 'macos-latest', image: '' }
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    steps:
      - uses: maxim-lobanov/setup-xcode@1.0
        with: { 'xcode-version': 'latest' }
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: actions/checkout@v2
      - run: swift test --enable-test-discovery --sanitize=thread
  driver-integration_all:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: 'macos-latest', image: '', psqlhost: '127.0.0.1', mysqlhost: '127.0.0.1' }
          - { os: 'ubuntu-latest', image: 'swift:5.2-bionic', psqlhost: psql, mysqlhost: mysql }
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    services:
      psql:
        image: postgres:latest
        env: { POSTGRES_DB: vapor_database, POSTGRES_USER: vapor_username, POSTGRES_PASSWORD: vapor_password }
      mysql:
        image: mysql:latest
        env: { MYSQL_ALLOW_EMPTY_PASSWORD: true, MYSQL_DATABASE: vapor_database, MYSQL_USER: vapor_username, MYSQL_PASSWORD: vapor_password }
    env:
      POSTGRES_HOSTNAME: ${{ matrix.psqlhost }}
      MYSQL_HOSTNAME: ${{ matrix.mysqlhost }}
      MYSQL_TLS: true
    steps:
      - run: apt update -q && apt install -y libsqlite3-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: maxim-lobanov/setup-xcode@1.0
        with: { 'xcode-version': 'latest' }
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Setup macOS servers
        run: |
          brew uninstall --force postgresql php && rm -rf /usr/local/{etc,var}/{postgres,pg}*
          brew install postgresql mysql
          initdb --locale=C -E UTF-8 $(brew --prefix)/var/postgres
          brew services start postgresql
          brew services start mysql
        if: ${{ matrix.os == 'macos-latest' }}
      - uses: actions/checkout@v2
        with: { path: sql-kit }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/fluent-kit', path: fluent-kit }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/sqlite-kit', path: sqlite-kit }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/fluent-sqlite-driver', path: fluent-sqlite-driver }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/postgres-kit', path: postgres-kit }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/fluent-postgres-driver', path: fluent-postgres-driver }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/mysql-kit', path: mysql-kit }
      - uses: actions/checkout@v2
        with: { repository: 'vapor/fluent-mysql-driver', path: fluent-mysql-driver }
      - run: |
          for p in {fluent,sqlite,postgres,mysql}-kit fluent-{sqlite,postgres,mysql}-driver; do
            swift package --package-path $p edit sql-kit --path sql-kit
          done      
      - run: swift test --package-path fluent-kit --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path sqlite-kit --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path fluent-sqlite-driver --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path postgres-kit --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path fluent-postgres-driver --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path mysql-kit --enable-test-discovery --sanitize=thread
        continue-on-error: true
      - run: swift test --package-path fluent-mysql-driver --enable-test-discovery --sanitize=thread
        continue-on-error: true
